services:
    victoire_core.widget_poll_content_resolver:
        class: Victoire\Widget\PollBundle\Resolver\WidgetPollContentResolver
        parent: victoire_widget.base_widget_content_resolver
        arguments:
            - "@form.factory"
            - "@router"
            - "@request_stack"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Poll }

    victoire.widget.poll:
        class: Victoire\Widget\PollBundle\Entity\WidgetPoll

    victoire.widget.form.poll:
        class: Victoire\Widget\PollBundle\Form\WidgetPollType
        arguments:
            - "@victoire.widget.poll.poll_configuration_chain"
        tags:
            - { name: form.type }
    victoire.widget.form.paticipation:
        class: Victoire\Widget\PollBundle\Form\Answer\ParticipationType
        arguments:
            - @victoire.widget.poll.poll_configuration_chain
        tags:
            - { name: form.type }

    victoire.widget.poll.poll_question_chain:
        class: Victoire\Widget\PollBundle\DependencyInjection\Chain\PollQuestionChain

    victoire_widget_poll_question:
        class: Victoire\Widget\PollBundle\Form\QuestionType
        arguments:
            - @victoire.widget.poll.poll_question_chain
        tags:
            - {name: form.type }
            - {name: victoire_widget_poll.question, questionType: "question"}

    victoire_widget_poll_radio:
        class: Victoire\Widget\PollBundle\Form\QuestionRadioType
        arguments:
            - @victoire.widget.poll.poll_question_chain
        tags:
            - {name: form.type }
            - {name: victoire_widget_poll.question, questionType: "radio"}

    victoire.widget.form.participation:
        class: Victoire\Widget\PollBundle\Form\Answer\ParticipationType
        arguments:
            - "@victoire.widget.poll.poll_configuration_chain"
        tags:
            - { name: form.type }

    victoire.widget.poll.poll_configuration_chain:
        class: Victoire\Widget\PollBundle\DependencyInjection\Chain\PollConfigurationChain

    victoire_widget_poll_question_default:
        class: Victoire\Widget\PollBundle\Form\Question\QuestionType
        arguments:
            - "@victoire.widget.poll.poll_configuration_chain"
        tags:
            - {name: form.type }

    victoire_widget_poll_answer_default:
        class: Victoire\Widget\PollBundle\Form\Answer\AnswerType
        arguments:
            - "@victoire.widget.poll.poll_configuration_chain"
        tags:
            - {name: form.type }

    victoire_widget_poll__question_radio:
        class: Victoire\Widget\PollBundle\Form\Question\QuestionRadioType
        parent: victoire_widget_poll_question_default
        tags:
            - {name: form.type }

    victoire_widget_poll__answer_radio:
        class: Victoire\Widget\PollBundle\Form\Answer\RadioAnswerType
        parent: victoire_widget_poll_answer_default
        tags:
            - {name: form.type }
    victoire_widget_poll.voting_subscriber:
        class: Victoire\Widget\PollBundle\EventSubscriber\VotingSubscriber
        arguments:
            - "%victoire_core.user_class%"
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, priority: 10}


    ## REPOSITORIES ##
    victoire_widget_poll.repository.participation:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Victoire\Widget\PollBundle\Entity\WidgetPoll

    ## VICTOIRE MENU ##
    victoire_widget_poll.victoire_menu_listener:
        class: Victoire\Widget\PollBundle\Listener\VictoireMenuListener
        arguments:
            - @victoire_core.admin_menu_builder
            - %victoire_widget_poll.victoire_menu_item%
        tags:
            - { name: kernel.event_listener, event: victoire_core.build_menu, method: addGlobal, priority: 80 }

    ## TWIG EXTENSIONS ##
    victoire_widget_poll.twig.results_extension:
        class: Victoire\Widget\PollBundle\Twig\ResultsExtension
        arguments:
            - @victoire_widget_poll.repository.participation
        tags:
            - { name: twig.extension }